// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpquyqxgleyhqcwqznqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwcXV5cXhnbGV5aHFjd3F6bnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjQ2OTksImV4cCI6MjA2MTQwMDY5OX0.ychhqyNOg7BC67j7K3qutWX0VHWSSpZeX881e7GXR2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);